allow templating directory names
Prince781/valdo pull request #6
Opened 2021-06-29 20:18 UTC by aeldemery

with this PR, one would be able to use variables inside project directory structures.

2021-06-29 20:52 UTC, Prince781 commented
Using `$` in folder names is a bit tricky, especially on Unix-like operating systems.

2021-06-29 21:11 UTC, aeldemery commented
But I have tested it `$` and it's an acceptable char in folder names.

2021-07-01 07:29 UTC, Prince781 commented
@aeldemery I take your point. My initial concern was the potential for uniquely bad consequences if a future bug results in file operations being attempted on folders that evaluate to `/`. It also may make it tricky to manipulate the folders with command line tools.

I think the motivation is good. Perhaps we could instead have, in the template file, a list of renamings to perform?

2021-07-01 07:32 UTC, Prince781 commented
Perhaps if you could explain further an example of how dollar signs are used in Tera or other templating engines, I would change my mind.

2021-07-01 07:42 UTC, Prince781 reviewed
Some thoughts.

2021-07-01 07:42 UTC, Prince781 commented on src/templateengine.vala
> +                    var new_name = dir_name + "//" + substituted_name;
I think you should use `Path.build_filename()` so that the right dir separator is always used.

2021-07-01 07:42 UTC, Prince781 commented on src/templateengine.vala
> +                if (folder_name.has_prefix ("${")) {
Perhaps this should be able to replace a variable anywhere in the folder name, not just at the beginning?

2021-07-01 11:22 UTC, aeldemery commented
Thank you for your review. 

For some of the code generating tools on github which use jinja2 and tera are [coockiecutter](https://github.com/cookiecutter/cookiecutter/tree/master/tests/files) and [kickstart](https://github.com/Keats/kickstart/tree/master/examples/slugify) respectively.

you are right, one should build paths using specified API rather than concatenating strings.
I will update the MR.
Thanks

2021-07-01 13:09 UTC, benwaffle commented
sbt new (via g8) supports it http://www.foundweekends.org/giter8/template.html

2021-07-02 16:11 UTC, Prince781 commented
So I'm inclined to support this PR after thinking it over. I still need you to make the changes I suggested.

2021-07-02 17:41 UTC, aeldemery commented
Sorry for late answer. I pushed the required suggestions.

2021-07-03 06:13 UTC, Prince781 requested changes

2021-07-03 06:13 UTC, Prince781 commented on src/templateengine.vala
> +                if (folder_name.contains ("${")) {
I think you might want to get rid of this `if` and just unconditionally substitute the directory name.

2021-07-07 06:39 UTC, aeldemery commented
@Prince781 sorry I've been busy lately. You can pick up with this PR and modify it at will or close it applying your own logic to obtain the same end result. Thank you.

2021-07-30 04:20 UTC, Prince781 commented
Unfortunately I can't push directly to your branch so I've made a new branch with some modifications.

2021-07-30 05:51 UTC, Prince781 commented
Closing this in favor of #8

2021-07-30 05:51 UTC, closed without merging